name: Daily Prompt

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python prompt_trick_send_slack.py